### ISSUE TITLE
Not updating since midnight 01-01-2023

### ISSUE THREAD

**Issue by reulnl** [jobvk/Home-Assistant-Windcentrale#72] opened 2023-01-01 10:36 UTC
### Checklist

- [X] I'm running the [latest](https://github.com/jobvk/Home-Assistant-Windcentrale/releases/latest) version of the Windcentrale integration.
- [X] I checked if there is not a duplicate issue with the same question.
- [X] I have read the [README.md](https://github.com/jobvk/Home-Assistant-Windcentrale/blob/master/README.md) page.
- [X] This issue is a bug related to the Windcentrale integration.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] I have filled out the issue template to the best of my ability.

### The problem

The last update for all of my windshares (De Bonte Hen, De Grote Geert and De Jonge Held) was on 31-12-2022. It looks like no new data can be received since 01-01-2023, however the last_reset values of the energy / energy_shares sensors is updated to 2023-01-01T00:00:00.

Therefore, there's a spike on 01-01-2023 between 00:00 and 01:00 within the Energy dashboard with all energy generated in 2022.

### What is version of Home Assistant Core did you recieve the bug?

2022.12.8

### What is version of Home Assistant Supervisor did you recieve the bug?

2022.12.1

### What is version of Home Assistant Supervisor?

9.4

### What is version of the Windcentrale integration?

0.2.6

### Additional information

<img width="1178" alt="Scherm­afbeelding 2023-01-01 om 11 35 08" src="https://user-images.githubusercontent.com/16373001/210167780-c3c189a9-a90b-4f1a-b54f-3fd61ce2d4f6.png">

<img width="949" alt="Scherm­afbeelding 2023-01-01 om 11 36 10" src="https://user-images.githubusercontent.com/16373001/210167794-af89eaea-603d-49cf-aae7-0d613811f119.png">

**Comment by jobvk** [comment] 2023-01-01 15:40
Indeed. But the problem appears to be with the API's and not with my code. And since today is Sunday, I don't think the problem will be fixed today either. I'll call wind central tomorrow and ask if they can fix the problem.

![image](https://user-images.githubusercontent.com/32730202/210176440-c3d74f3a-c726-47ce-81b0-8ce71e68afb3.png)

**Comment by pcdiks** [comment] 2023-01-04 11:25
Any news from windcentrale? Looks like they have more problems. The website does not show live production at the moment…

**Comment by sebastianberm** [comment] 2023-01-04 13:45
Due to the fact I'm usually a pain in the ar** of everyone, I decided I'd call them. They don't know anything about any problems.
It was written down and they'd get back to me via e-mail.

As for the more technical side; their API started giving back empty json blobs, so there is nothing that can be done from this integration.
If you want to call them, it's possible, but be prepared to have to wait for like 20 to 30 minutes before getting through to someone.

**Comment by reulnl** [comment] 2023-01-04 17:10
I've also contacted them via their contact form within "Mijn Windcentrale" yesterday, but no response so far.

**Comment by jobvk** [comment] 2023-01-04 19:14
Indeed, they have a customer service. But if you call, you can indeed count on a long wait. Emails also take an average of a few days to be answered. This could also be because they may have outsourced their customer service to a 3rd party. 

The problem is also that the website and APIs are also developed by a 3rd party. So customer service indeed has no knowledge of the APIs.

I also called and got the same response that my problem was written down and I would get an email when the problem would be solved. But they could not give a time when the problem would be solved approximately.

**Comment by jwstekelenburg** [comment] 2023-01-08 00:14
> I've also contacted them via their contact form within "Mijn Windcentrale" yesterday, but no response so far.

Same here

**Comment by QNimbus** [comment] 2023-01-08 14:44
I've also contacted windcentrale - no response yet

**Comment by ronaldvdvelden** [comment] 2023-01-09 16:24
Communication lacks a more and more. Looking at the webcam I notice that Het Rode Hert is not working for a couple of days already

**Comment by abko** [comment] 2023-01-11 13:48
I reached out and got this comment (in Dutch):

> Bedankt voor je reactie!
> Ook jij een gelukkig nieuwjaar toegewenst.
>  
> Helaas heb ik wat slechter nieuws.
> Momenteel is er een probleem met het ophalen van alle data van het meetbedrijf.
> Hierdoor klopt het dat er niets binnen kan komen.
> De molen produceert wel gewoon groene stroom!
>  
> We zijn hiermee druk aan de slag gegaan.
> We hopen dit zo snel mogelijk weer volledig zichtbaar te krijgen voor al onze klanten.
>  
> Ook kijken we ofdat we nog hierover een bericht gaan plaatsen.
> Dit zou je dan kunnen vinden onder het kopje 'Berichten'.
>  
> Excuses voor het ongemak.
> Wens ik je toch nog een fijne dag!
> Met vriendelijke groet,
> 
> Emma
> Klantenservice medewerker


It's still offline, you can check via https://mijn.windcentrale.nl/account and you login. It's not reporting anything yet.

I did ask them to start updating the message section with status and progress again, but have not seen them do that.

**Comment by ronaldvdvelden** [comment] 2023-01-12 16:12
Just received a message that the problem should be solved. I can’t see it because apparently Het Rode Hert has an issue since 20-12-2022. It hasn’t run since.

**Comment by abko** [comment] 2023-01-12 16:14
@ronaldvdvelden Nothing for De Jonge Held yet...

<img width="504" alt="image" src="https://user-images.githubusercontent.com/360683/212120995-8e6a294f-dd11-49e1-aaf2-2c2a744468b2.png">

**Comment by abko** [comment] 2023-01-12 16:16
On a positive note. They started adding messages again. Have a look at mijn wind centrale to see more (also about the bug that messages are not correctly displayed).

<img width="988" alt="image" src="https://user-images.githubusercontent.com/360683/212121649-b414408d-9e12-453f-906f-4f55c0f04d28.png">

**Comment by achilleus68** [comment] 2023-01-12 17:44
The news is updated in my HA instance, but the production not yet

![afbeelding](https://user-images.githubusercontent.com/1582516/212140381-94318d7c-ec05-419d-9b7a-4a4f4df2db4f.png)

![afbeelding](https://user-images.githubusercontent.com/1582516/212140475-08b3fb3c-e156-424e-ad3e-41fde03656ae.png)

**Comment by gerard76** [comment] 2023-01-17 13:42
Got an update today: "[...]Wanneer het is opgelost is nog niet bekend. [...]"

**Comment by achilleus68** [comment] 2023-01-31 19:17
Looks like they got it working again since 3pm CET today

![afbeelding](https://user-images.githubusercontent.com/1582516/215860433-ba9601db-6674-4d19-8aba-d1c7afab0df0.png)
![afbeelding](https://user-images.githubusercontent.com/1582516/215860670-8b1aa868-e82b-41a1-856e-adf309fd545a.png)


Is it possible to correct the historical data via the add-on?

**Comment by Simanias** [comment] 2023-01-31 19:24
Yes here it's working as well. Only the energy management entity is not (yet) working.

**Comment by ronaldvdvelden** [comment] 2023-01-31 20:57
> Looks like they got it working again since 3pm CET today
> 
> ![afbeelding](https://user-images.githubusercontent.com/1582516/215860433-ba9601db-6674-4d19-8aba-d1c7afab0df0.png) ![afbeelding](https://user-images.githubusercontent.com/1582516/215860670-8b1aa868-e82b-41a1-856e-adf309fd545a.png)
> 
> Is it possible to correct the historical data via the add-on?

You can do that via the developers-tool

**Comment by achilleus68** [comment] 2023-02-01 17:52
Not for the Energy dashboard, I think?
![afbeelding](https://user-images.githubusercontent.com/1582516/216123336-08467301-04f9-44a2-98ac-d62e5e626b88.png)

**Comment by krispijnb** [comment] 2023-02-01 19:43
Got the same issue yesterday with an enormous spike in energy use. But today (February 1st) the energy dashboard is up and running again including Windcentrale
![Schermafdruk van 2023-02-01 20-42-07](https://user-images.githubusercontent.com/114363866/216146550-55f6afbe-7d5d-411a-9c42-a6ef7ffacf0c.png)
.

**Comment by ronaldvdvelden** [comment] 2023-02-01 20:04
> Got the same issue yesterday with an enormous spike in energy use. But today (February 1st) the energy dashboard is up and running again including Windcentrale ![Schermafdruk van 2023-02-01 20-42-07](https://user-images.githubusercontent.com/114363866/216146550-55f6afbe-7d5d-411a-9c42-a6ef7ffacf0c.png) .

I am having issues with Het Rode Hert, do you have shares of that mill? It states it's missing month 2 in the total/shares data

**Comment by krispijnb** [comment] 2023-02-01 20:56
I don't have shares in Het Rode Hert, but at closer look I'm missing the shares of De Trouwe Wachter. So it looks like the api is partly up, but not completely.

**Comment by gerard76** [comment] 2023-02-02 13:54
No updates here. Weird.
- Grote Geert
- Trouwe Wachter
- Vier Winden

**Comment by Xorfor** [comment] 2023-02-02 22:37
![image](https://user-images.githubusercontent.com/32778657/216465390-717056ea-5924-4bad-b36f-24ea63d1f5d1.png)
It seems that I get some data now!

**Comment by Xorfor** [comment] 2023-02-02 22:42
![image](https://user-images.githubusercontent.com/32778657/216466309-5ead6c11-1b07-4d88-b706-a5833ae483ef.png)

**Comment by Xorfor** [comment] 2023-02-02 22:43
Restart your system!

**Comment by pcdiks** [comment] 2023-02-03 08:43
It's working for me except for two windmills that I added to the energy dashboard
![image](https://user-images.githubusercontent.com/16719277/216548076-04e6b779-fdaf-4b30-8b44-af745d06b876.png)

De Trouwe Wachter and Het Rode Hert do not show the correct info in the energy dashboard. It does have other info like this:
![image](https://user-images.githubusercontent.com/16719277/216553057-eb75cdab-79b8-4e87-8583-1c4b3850659b.png)

**Comment by achilleus68** [comment] 2023-02-03 15:52
How can we remove _statistics_? And what have you deleted?

**Comment by Xorfor** [comment] 2023-02-03 20:05
I don't get Energy from Trouwe Wachter yet

**Comment by jobvk** [comment] 2023-02-03 21:15
@achilleus68 > ~How can we remove _statistics_?~ And what have you deleted?

I removed _statistics_ that made it look like there was a massive drop/spike like with @reulnl.
I made some instructions on how to fix this https://github.com/jobvk/Home-Assistant-Windcentrale/discussions/76

**Comment by jmarijne** [comment] 2023-02-09 16:08
> ![Schermafbeelding_20230203_211612](https://user-images.githubusercontent.com/32778657/216702393-0e24b0a4-e476-4fe2-b712-382f0f0ba95e.png) I don't get Energy from Trouwe Wachter yet

same problem here, some stats come in but not energy production values both on Trouwe wachter and Rode hert
![image](https://user-images.githubusercontent.com/16038268/217868947-7ac5be35-5dce-498e-a4c0-8b8809a160bd.png)

**Comment by Xorfor** [comment] 2023-02-13 19:50
@jobvk Done 😃

**Comment by ronaldvdvelden** [comment] 2023-02-15 08:37
I created a support request for the missing data at the servicedesk of Windcentrale. They want a photo of what I am seeing. As I am abroad could some post an image of the api or home-assistant I can sent to them?

**Comment by jobvk** [comment] 2023-02-15 08:55
@ronaldvdvelden
Here are the api results

year_runtime, total_runtime and year_production are missing of the windturbines:

Trouwe Wachter
``` json
{
   "WND-TW":{
      "diameter":"33",
      "year_runtime":"0",
      "total_runtime":"0",
      "rpm":"21.5",
      "year_production":"0",
      "wind_direction":"Z",
      "power":"171",
      "wind_power":"5",
      "timestamp":"1676451061",
      "id":"121",
      "power_per_share":"31",
      "power_percentage":"21",
      "pulsating":"0"
   }
}
```

Rode Hert
``` json
{
   "WND-RH":{
      "diameter":"32",
      "year_runtime":"0",
      "total_runtime":"0",
      "rpm":"13.4",
      "year_production":"0",
      "wind_direction":"ZO",
      "power":"392",
      "wind_power":"4",
      "timestamp":"1676451130",
      "id":"31",
      "power_per_share":"59",
      "power_percentage":"20",
      "pulsating":"0"
   }
}
```

**Comment by Xorfor** [comment] 2023-02-20 18:07
@jobvk Do you also have the correct data from De Grote Geert?

They also asked me for 'screendumps'. I want to send them both De Grote Geert and de Trouwe Wachter.

**Comment by ronaldvdvelden** [comment] 2023-02-20 18:47
> @jobvk Do you also have the correct data from De Grote Geert?
> 
> 
> 
> They also asked me for 'screendumps'. I want to send them both De Grote Geert and de Trouwe Wachter.

Hi,

Initially I only send the json output. Got a reply that they only saw some numbers 🫣 and asked for a screenshot. So I included a screenshot of all the available data of Het Rode Hert within Home-Assistant

![image](https://user-images.githubusercontent.com/46248573/220180646-062c83f2-a494-4d72-9524-d965cded18fa.png)

**Comment by jobvk** [comment] 2023-02-22 21:04
> @jobvk Do you also have the correct data from De Grote Geert?
> 
> They also asked me for 'screendumps'. I want to send them both De Grote Geert and de Trouwe Wachter.
``` json
{
   "WND-GG":{
      "id":"1",
      "timestamp":"1677099720",
      "wind_power":"3",
      "power":"42",
      "wind_direction":"ZW",
      "year_production":"912483",
      "rpm":"8.2",
      "total_runtime":"121317",
      "year_runtime":"1220.000000",
      "diameter":"13",
      "pulsating":"0",
      "power_percentage":"2",
      "power_per_share":"5"
   }
}
```

**Comment by mschut** [comment] 2023-03-14 04:28
I am sorry, didn't read well enough... Just have contacted Windcentrale as well for the missing data of Het Rode Hert.

**Comment by gerard76** [comment] 2023-03-14 16:42
still nothing on those two?

**Comment by ronaldvdvelden** [comment] 2023-03-14 17:50
> still nothing on those two?

I asked this week once more and they still didn't have a solution for the missing data

**Comment by mschut** [comment] 2023-03-25 08:03
I asked as well, included the info from here. Reaction was the same: "Can you send a screenshot". I dont know a screenshot of what? Too bad. yesterday was a nice windy day, in my energy overview I wished I could see all my windshares.

**Comment by Xorfor** [comment] 2023-03-29 13:23
For people who can not wait for the fix (I don't expect this anymore), here is a workaround:

First we convert the power in W of your windmill shares to Wh:

1. In HA go to Settings -> Devices & Services -> Helpers
2. Click on [+ Create Helper]
3. Choose 'Integration - Riemann sum integral sensor'
4. Give this sensor a name, eg. <your windmill> - Riemann
5. For sensor, select you windmill, this will be 'sensor.<your windmill>', the sensor that provides you the current power of your windmill shares in W.
6. Further setting:
  - Integration method: Left
  - Precision: 2
  - Metric prefix: none
  - Time unit: hours
7. Click on [Submit]
8. Click on [Finish]

Now we want to get the energy in Wh per day from the previous helper:
1. Click on [+ Create Helper]
2. Choose 'Utility Meter'
3. Give this sensor a name, eg. <your windmill> - Energy per day
4. For Input sensor, select the helper you created in the previous steps
5. Further settings:
  - Meter reset cycle: Daily
  - For other setting: use the defaults
6. Click on [Submit]
7. Click on [Finish]

Now you can use the last created helper, to display the energy production from your windmill shares, or do other calculations.
I have tested this a couple of days, and get roughly the same results, enough to do my calculations, and this is better then nothing :)

**Comment by mschut** [comment] 2023-03-29 17:44
Thanks! Followed your guideline directly. However, I would like to add the windmill to the energy dashboard. I dont seem to be able to add the second helper. Do I need to add another helper for this?

**Comment by mschut** [comment] 2023-03-30 05:29
I was too eager. I just added your second helper to the Energy dashboard, it works like a charm!

**Comment by pcdiks** [comment] 2023-03-30 12:47
Strange, I added this for two windmills, De Trouwe Wachter and Het Rode Hert. It works for Het Rode Hert but it does not work for De Trouwe Wachter... The two riemann helpers also have a different icon:
![image](https://user-images.githubusercontent.com/16719277/228840306-f7531dc7-eaf1-47fb-b909-4cbd3b03c2da.png)

Any ideas?

**Closed** 2023-05-19 09:53 UTC
Labels: bug
