### ISSUE TITLE
Invalid response from server for collection live data of windturbine 

### ISSUE THREAD

**Issue by bliekp** [jobvk/Home-Assistant-Windcentrale#18] opened 2022-05-04 10:47 UTC
### Checklist

- [X] I'm running the [latest](https://github.com/jobvk/Home-Assistant-Windcentrale/releases/latest) version of the Windcentrale integration.
- [X] I checked if there is not a duplicate issue with the same question.
- [X] I have read the [README.md](https://github.com/jobvk/Home-Assistant-Windcentrale/blob/master/README.md) page.
- [X] This issue is a bug related to the Windcentrale integration.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] I have filled out the issue template to the best of my ability.

### The problem

Since two days the live data is no longer updated. My logs are flooded with the following:

### What is version of Home Assistant Core did you recieve the bug?

core-2022.4.7

### What is version of Home Assistant Supervisor did you recieve the bug?

supervisor-2022.05.0

### What is version of Home Assistant Supervisor?

Home Assistant OS 7.6

### What is version of the Windcentrale integration?

0.1.4

### Anything in the logs that might be useful for us?

2022-05-04 12:44:42 ERROR (MainThread) [custom_components.windcentrale.wind] Invalid response from server for collection live data of windturbine De Blauwe Reiger
2022-05-04 12:44:42 ERROR (MainThread) [custom_components.windcentrale.wind] Invalid response from server for collection live data of windturbine De Ranke Zwaan
2022-05-04 12:44:42 ERROR (MainThread) [custom_components.windcentrale.wind] Invalid response from server for collection live data of windturbine De Jonge Held
2022-05-04 12:44:49 ERROR (MainThread) [custom_components.windcentrale.wind] Invalid response from server for collection production data of windturbine De Jonge Held
2022-05-04 12:44:49 ERROR (MainThread) [custom_components.windcentrale.wind] Invalid response from server for collection production data of windturbine De Ranke Zwaan
2022-05-04 12:44:49 ERROR (MainThread) [custom_components.windcentrale.wind] Invalid response from server for collection production data of windturbine De Blauwe Reiger
2022-05-04 12:44:53 ERROR (MainThread) [custom_components.windcentrale.wind] Invalid response from server for collection live data of windturbine De Ranke Zwaan
2022-05-04 12:44:53 ERROR (MainThread) [custom_components.windcentrale.wind] Invalid response from server for collection live data of windturbine De Blauwe Reiger
2022-05-04 12:44:53 ERROR (MainThread) [custom_components.windcentrale.wind] Invalid response from server for collection live data of windturbine De Jonge Held
2022-05-04 12:45:03 ERROR (MainThread) [custom_components.windcentrale.wind] Invalid response from server for collection live data of windturbine De Jonge Held
2022-05-04 12:45:03 ERROR (MainThread) [custom_components.windcentrale.wind] Invalid response from server for collection live data of windturbine De Ranke Zwaan
2022-05-04 12:45:03 ERROR (MainThread) [custom_components.windcentrale.wind] Invalid response from server for collection live data of windturbine De Blauwe Reiger
2022-05-04 12:45:13 ERROR (MainThread) [custom_components.windcentrale.wind] Invalid response from server for collection live data of windturbine De Blauwe Reiger
2022-05-04 12:45:13 ERROR (MainThread) [custom_components.windcentrale.wind] Invalid response from server for collection live data of windturbine De Ranke Zwaan
2022-05-04 12:45:13 ERROR (MainThread) [custom_components.windcentrale.wind] Invalid response from server for collection live data of windturbine De Jonge Held
2022-05-04 12:45:23 ERROR (MainThread) [custom_components.windcentrale.wind] Invalid response from server for collection live data of windturbine De Blauwe Reiger
2022-05-04 12:45:23 ERROR (MainThread) [custom_components.windcentrale.wind] Invalid response from server for collection live data of windturbine De Ranke Zwaan
2022-05-04 12:45:23 ERROR (MainThread) [custom_components.windcentrale.wind] Invalid response from server for collection live data of windturbine De Jonge Held

**Comment by bliekp** [comment] 2022-05-04 13:30
Of course it's very possible the cause is at the Windcentrale's end, but I wouldn't know how to debug this.

**Comment by jobvk** [comment] 2022-05-04 14:36
When I check the API's for both login and data retrieval, they both give a 503 error. Logging in via the [site](https://mijnmolen.windcentrale.nl/#/login) is also currently unavailable.

I will try to contact the company and ask what the situation is and if the current system is out of order or if there is a new system coming.

**Comment by jobvk** [comment] 2022-05-04 14:56
> I wouldn't be surprised if it is caused by the Windcentrale itself, and also if its correlated with my posted issue: they are working on ( as they call it) a new frontend and I wouldn't be surprised if the api used is end of life.

Indeed they create a new platform [https://mijn.windcentrale.nl/](https://mijn.windcentrale.nl/). I'm going to try to read the data from this. But this is probably going to take some time as it is a brand new platform with new APIs.

**Comment by bliekp** [comment] 2022-05-04 18:20
Thanks for the effort Job! I'll buy you a beer if you succeed! :)

**Comment by jobvk** [comment] 2022-05-04 19:11
For now I can only find this screen with little data. Also in the APIs that are used for this there is not much data.

![image](https://user-images.githubusercontent.com/32730202/166808592-51902205-38ec-419d-98cf-0859a7ee5c05.png)

If anyone can find a screen with more data I'd really appreciate it. I will keep an eye on the site in the near future and hope that more data will become available.

**Comment by mschut** [comment] 2022-05-06 07:58
PS: I do have some values again in HA for the moment

**Comment by jobvk** [comment] 2022-05-06 08:13
> S: I do have some values again in HA for the moment

It looks like it's working for now. But I'm still going to look at the new platform because they will switch at some point.

**Comment by jobvk** [comment] 2022-05-20 19:42
Looks like they are working on it
![image](https://user-images.githubusercontent.com/32730202/169600170-3690a5d4-2009-41d2-8232-8d87499f0323.png)

**Comment by jobvk** [comment] 2022-06-28 14:08
I'm going to close this issue for now. I have created a new issue #26 for the new platform.

**Closed by jobvk** 2022-06-28 14:08 UTC
Labels: bug

**Comment by jobvk** [comment] 2022-08-22 18:08
@bliekp The problem is solved in the new version 0.2.x
